version: '3.8'
services:
  library-app:
    build: .
    ports:
      - "3000:3000"
  counter-app:
    build: ../count
    ports:
      - "3001:3001"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
